apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: openfinance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - consumer
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: consumer
          image: openfinance/consumer:latest
          imagePullPolicy: Never
          env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "kafka.openfinance.svc.cluster.local:9092"
          - name: REDIS_ADDR
            value: "redis.openfinance.svc.cluster.local:6379"