apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
  namespace: openfinance
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: load-test
          image: ghcr.io/freyrecorona/openfinance-test/loadtest:latest
          command: ["/loadtest"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.openfinance.svc.cluster.local:9092"
            - name: REDIS_ADDR
              value: "redis.openfinance.svc.cluster.local:6379"